name: Code Styling and Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - "**.py"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install and Run Isort
        run: |
          python -m pip install isort
          python -m isort .
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install and Run Black
        run: |
          python -m pip install black
          python -m black .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install and Run Mypy
        run: |
          python -m pip install mypy
          python -m mypy lemon
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install and Run Pytest
        run: |
          python -m pip install pytest
          python -m pytest tests
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install and Run Pylint
        run: |
          python -m pip install pylint
          pylint lemon